export type TCar = {
  _id: string;
  name: string;
  model: string;
  year: string;
  image: string;
  location: string;
  ownerEmail: string;
  ownerName: string;
  description: string;
  color: string;
  isElectric: boolean;
  status: string;
  features: string[];
  pricePerHour: number;
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string;
  __v: number;
};
